name: Input or GITHUB_REF name
description: Returns either the name given via input or parses it from GITHUB_REF
author: AlmirKadric

# branding:
#     icon:
#     color:

inputs:
    target-ref:
        description: >
            The `name` we should use if available before trying to parse `name`
            from `GITHUB_REF`.

outputs:
    ref:
        description: The resulting raw ref
        value: ${{ steps.get-ref.outputs.ref }}
    ref-name:
        description: Resulting ref name
        value: ${{ steps.get-ref.outputs.ref-name }}

runs:
    using: 'node20'
    main: ./main.js
