name: Node.js Subsystem Script
description: Setup a Node.js subsystem project and run a NPM script
author: AlmirKadric

# branding:
#     icon:
#     color:

inputs:
    token:
        description:
        default: ${{ github.token }}
    target-ref:
        description: >
            The git ref we should setup the job against. This defaults to the
            SHA or ref of the event which triggered the job.

            ※ This is a proxy to the `target-ref` input for the `katalyststack/github-actions/input-or-ref-name` action.
            ※ This is a proxy to the `ref` input for the `actions/checkout` action.
        default: ''
    node-version:
        description: >
            Node.js version to setup. This defaults to '20' if not provided.

            ※ This is a proxy to the `node-version` input for the `actions/setup-node` action.
        default: '20'
    cache-path:
        description: >
            Newline seperated list of path(s) which should be cached. This
            defaults to `./node_modules` if not provided.

            ※ This is a proxy to the `path` input for the `actions/cache` action.
        default: |
            ./node_modules
    cache-salt:
        description: >
            Random salt to put at the end of cache key
            The `` default will be used if not provided.
    npm-script:
        description: >
            The name of the npm script to run. This defaults to 'test' if not
            provided.
        default: test

runs:
    using: 'node20'
    main: ./main.js
    post: ./post.js
    post-if: 'success()'
